- cmd/moco-agent/cmd/server.go
- go.mod
- server/rotate.go
- server/rotate_test.go
refs: https://github.com/cybozu-go/moco/issues/173
Use `github.com/robfig/cron` to run logrotate based on the cron spec rather than the API.
Added the `log-rotation-schedule` option for this purpose. This option is configured by the controller based on the `MySQLCluster.spec.logRotationSchedule`.
> Deprecate the rotate API and use goroutine to periodically run cron job

- cmd/moco-agent/cmd/init.go
- cmd/moco-agent/cmd/ping.go
- cmd/moco-agent/cmd/root.go
- cmd/moco-agent/cmd/server.go
- constants.go
- initialize/init.go
- initialize/init_test.go
- server/backup_binlog.go
- server/backup_binlog_test.go
- server/clone.go
- server/clone_test.go
- server/health.go
- server/health_test.go
- server/rotate.go
- server/rotate_test.go
- server/server.go
- test_utils/mysql.go
This PR includes:
- Remove `root` user for MySQL
- Rename `MiscUser = "moco-misc"` to `AgentUser = "moco-agent"`
- Remove `OperatorUser = "moco-operator"` because it's not used
- Only rename variable `OperatorAdminUser` to `AdminUser`
- Copy some constants from `cybozu-go/moco` and fix to follow the above renaming
> Drop root user and rename misc to agent user.

- .github/workflows/release.yaml
https://github.blog/changelog/2021-03-24-packages-container-registry-now-supports-github_token/
> Use GITHUB_TOKEN to push images

- cmd/moco-agent/cmd/root.go
When the default prometheus registry is used, the gRPC metrics
has been automatically registered within the library.
The original code registered the metrics twice and caused a panic.
> Fix panic on registering gRPC metrics

- CHANGELOG.md
- Dockerfile
- RELEASE.md
- cmd/moco-agent/cmd/root.go
- docs/metrics.md
- metrics/metrics.go
- server/clone.go
- server/initialize.go
- server/mysql_status.go
- server/mysqld_health.go
- server/rotate.go
- server/rotate_test.go
- server/server.go
- server/suite_test.go
If the donor instance is also a MOCO cluster, it has its own MOCO users.
The passwords for them need to be reset after cloning the data.
This PR also includes a change to the metrics implementation.
> Reset user passwords after cloning data

- CHANGELOG.md
- cert/cert.go
- cmd/moco-agent/cmd/root.go
moco-agent now serves TLS and requires client certificate from
a valid CA whose CommonName must match "moco-controller".
See https://github.com/cybozu-go/moco/issues/21
> Implement mTLS for gRPC

- CHANGELOG.md
- server/initialize.go
required for `mysqlbinlog` command.
> Grant `REPLICATION SLAVE` to moco-backup user.

- cmd/moco-agent/cmd/root.go
This PR fixes the problem that a server sends a GOAWAY with ENHANCE_YOUR_CALM if the client sends too many misbehaving pings.
See
https://grpc.github.io/grpc/core/md_doc_keepalive.html
> Set KeepaliveEnforcementPolicy

- server/clone.go
This PR fixes the problem that the clone operation fails if the moco controller Pod is terminated during the operation.
moco-agent can not complete the operation, since post-process after the clone is aborted in that situation.
> Wait mysqld bootstrap even if a cancel signal is received

- Dockerfile
- cmd/cp/main.go
- cmd/moco-init/main.go
- cmd/moco-init/my.cnf
- go.mod
- go.sum
refs: https://github.com/cybozu-go/moco/issues/442
Currently, moco-init is built into the MySQL image, but versioning is difficult.
https://github.com/cybozu/neco-containers/blob/main/mysql/moco-init/main.go
This change will include moco-init in the moco-agent container.
moco-agent is version-controlled, making it easier to manage additional features.
moco-controller uses the moco-init binary copied from the moco-agnet container with the cp command:
```yaml
initContainers:
- command:
- cp
- /moco-init
- /shared/moco-init
image: ghcr.io/cybozu-go/moco-agent:0.7.1
```
> Add moco-init and lower-case-table-names flags

- .github/workflows/release.yaml
Use `gh` command instead of `actions/create-release` and `actions/upload-release-asset`.
Because the actions have been archived.
> Use gh command

- cmd/moco-agent/cmd/root.go
- docs/moco-agent.md
- server/clone_test.go
- server/mysql_status.go
- server/mysqld_health.go
- server/mysqld_health_test.go
- server/rotate_test.go
- server/server.go
In case of replica instance, return "not ready" if no transaction is received soon after process start.
cf. internal request NECOREQ-383
Signed-off-by: UMEZAWA Takeshi <takeshi-umezawa@cybozu.co.jp>
> add an option for waiting transaction queueing on replica

- server/mysqld_health.go
Signed-off-by: UMEZAWA Takeshi <takeshi-umezawa@cybozu.co.jp>
> output replication lag metrics even if delay check is skipped

- Makefile
custom-checker will be moved from `cybozu/neco-containers/golang` to `cybozu-go/golang-custom-analyzer`.
> Replace custom-checker

- server/clone.go
- server/connect.go
Partial fix for cybozu-go/moco#630
> Fix moco#630

- cmd/moco-agent/cmd/root.go
- cmd/moco-init/main.go
When running with istio enabled the communication between the agent and mysqld fails. To overcome this the admin interface for mysqld should be bound to `localhost` and the agent should communicate on `localhost` as well, rather than using pod name.
[More context here](https://github.com/cybozu-go/moco/pull/658#issuecomment-2012142633)
There will need to be more work to enable this configuration in https://github.com/cybozu-go/moco
> Option to to use localhost instead of pod name

- .github/workflows/ci.yaml
- server/mysql_test.go
- server/suite_test.go
https://github.com/cybozu-go/moco-agent/issues/77
Due to the spec change of docker official MySQL images, the moco-agent test no longer passes.
So I will change the test with the [moco/mysql](https://github.com/cybozu-go/moco/pkgs/container/moco%2Fmysql) images.
`moco/mysql` images do not initialize the MySQL's data directory. So, I initialize the data directory in `StartMySQLD()`.
> Test with moco/mysql container

- cmd/moco-agent/cmd/root.go
- server/connect.go
https://github.com/cybozu-go/moco-agent/issues/98
> issue-98: Fixed determination of whether root user exists or not

- cmd/moco-agent/cmd/root.go
- constants.go
- docs/moco-agent.md
- server/rotate.go
- server/rotate_test.go
> Add log-rotation-size option

- .github/actions/setup-aqua/action.yaml
- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- Makefile
- README.md
- aqua-checksums.json
- aqua.yaml
This pull request introduces the Aqua CLI as a toolchain manager for the project, streamlining the installation and management of development tools. The changes include the addition of a custom GitHub Action for setting up Aqua, updates to workflows to integrate Aqua, and modifications to the `Makefile` to simplify tool dependencies. Additionally, new documentation and configuration files for Aqua are included.
> Manage CLI tools by aquaproj/aqua
