.github/workflows/release.yaml, Dockerfile, README.md, ping.sh
=> Add release workflow of ghcr.

Dockerfile, Makefile, cmd/moco-agent/cmd/init.go, cmd/moco-agent/cmd/ping.go, cmd/moco-agent/cmd/root.go, cmd/moco-agent/main.go, ping.sh
=> Move ping function to moco-agent.

initialize/Dockerfile
=> Test with docker official image

cmd/moco-agent/cmd/server.go, constants.go, go.mod, server/backup_binlog.go, server/backup_binlog_test.go, server/clone_test.go, server/health_test.go, server/rotate_test.go, server/suite_test.go, test_utils/minio.go, test_utils/mysql.go, test_utils/run.go
=> Implement backup binlog API.

server/rotate.go
=> Simplify log rotation method

initialize/init.go, initialize/init_test.go
=> Remove all files before initialization

RELEASE.md
=> Update the procedure of publishing the GitHub release page

docs/metrics.md, metrics/metrics.go, metrics/updater.go, server/backup_binlog.go, server/backup_binlog_test.go, server/clone.go, server/clone_test.go
=> Add metrics representing in-progress state.

server/health.go, server/health_test.go, test_utils/mysql.go
=> Set state as not ready if MySQL thread has an error.

docs/server-apis.md, server/agentrpc/agentrpc.proto
=> Add descriptions for gRPC APIs.

Dockerfile
=> Add grpc-health-probe licence to Docker image.

cmd/moco-agent/cmd/root.go, initialize/mysql_plugins.go, initialize/mysql_plugins_test.go, initialize/mysql_users_test.go, initialize/suite_test.go, initialize/utils.go
=> Ensure plugins required by MOCO

CHANGELOG.md, constants.go, server/initialize.go, server/initialize_test.go, server/mysql_test.go
=> Add moco-exporter and moco-backup users

CHANGELOG.md, server/clone.go, server/connect.go, server/server.go
This commit also fixes a connection leak.
=> Fix timeout when cloning large data

server/initialize.go
https://github.com/cybozu-go/moco/issues/287
=> Grant PROXY privilage to AdminUser

LICENSE
All the committers so far belong to Cybozu.
=> Change LICENSE from MIT to Apache2

.github/workflows/ci.yaml, Makefile, server/mysql_test.go
refs: https://github.com/cybozu-go/moco/issues/285
=> Upgrade mysql version to 8.0.26

.github/workflows/ci.yaml, Makefile, server/mysql_test.go
same as https://github.com/cybozu-go/moco-agent/pull/62.
=> Support MySQL 8.0.28

cmd/moco-agent/cmd/root.go, docs/moco-agent.md
Signed-off-by: morimoto-cybozu <kenji_morimoto@cybozu.co.jp>
=> Add description about `--max-delay 0`

.github/workflows/ci.yaml, .github/workflows/release.yaml, Dockerfile
Use Ubuntu 22.04 in CI and docker build stage.
This update need not release.
=> Use Ubuntu 22.04

server/mysqld_health.go
cf. https://github.com/cybozu-go/moco-agent/issues/81
Signed-off-by: UMEZAWA Takeshi <takeshi-umezawa@cybozu.co.jp>
=> add a comment for non-intuitive behavior about zero values of TIMESTAMP and time.Time

Dockerfile, go.mod, go.sum
This PR includes below
- Upgrade go to 1.21
- Update direct dependencies
=> Upgrade go to 1.21 and update dependencies

Dockerfile
Signed-off-by: Daichi Sakaue <daichi-sakaue@cybozu.co.jp>
=> Migrate to ghcr.io
